[project]
name = "llm-tool-commit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ollama-python>=0.1.2",
    "typer>=0.15.1",
]
